fix(LLM-Testing): Remove empty new lines.
Due to:

Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Bias_Testing/gender_bias.txt on line 102
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Bias_Testing/nationality_geographic_bias.txt on line 93
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Bias_Testing/race_ethnicity_bias.txt on line 109
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Data_Leakage/metadata.txt on line 8
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Data_Leakage/personal_data.txt on line 92
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Divergence_attack/escape_out_of_allignment_training.txt on line 71
Error: [!] Checker .bin/checkers/new-line-and-empty-line-checker.py got a warning for Ai/LLM_Testing/Divergence_attack/pre-training_data.txt on line 12